"use client"
import React from 'react';
import { Layout, Space } from 'antd';
import Image from 'next/image';
import logo_blue from '@/images/logo_blue.png';
import BrandCard from '@/app/components/dashboard/brandCard/index.js';
import NavMenu from '@/app/components/dashboard/navigationMenu';
import TopMenu from '@/app/components/dashboard/topMenu';
const { Header, Sider, Content } = Layout;
const headerStyle = {
    display: 'flex',
    borderBottom: '1px solid #e8e8e8',
    textAlign: 'center',
    height: 'fit-content',
    paddingInline: 50,
    lineHeight: '64px',
    backgroundColor: '#FFFFFF',
};
const contentStyle = {
    display: 'flex',
    justifyContent: 'flex-start',
    flexDirection: 'column',
    // alignVertical: 'start',
    minHeight: 120,
    lineHeight: '120px',
    backgroundColor: '#FFFFFF',
    height: '90vh',
};
const siderStyle = {
    textAlign: 'center',
    lineHeight: '120px',
    color: '#ffff',
    backgroundColor: '#ffffff',
    height: '100vh',
    borderRight: '1px solid #e8e8e8',
};

// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Layout>
                    <Sider width={'25vw'} style={siderStyle} className='pt-6'>
                        <Space align='center' direction='vertical'>
                            <Image src={logo_blue} alt="navbar logo" height={50} className='pb-6' />
                            <BrandCard />
                            <NavMenu />
                        </Space>
                    </Sider>
                    <Layout>
                        <Header style={headerStyle}>
                            <TopMenu />
                        </Header>
                        <Content style={contentStyle}>
                            {children}
                        </Content>
                    </Layout>
                </Layout>
            </body>
        </html>
    )
}
